### PR TITLE
fix str decode error in Python 3 when summary is empty.

### PR DESCRIPTION
**Pull request by junfenglx**
Thanks

### CODE REVIEW

**Comment by junfenglx** [comment]
And another minor issue is if latex equations appear in summary in index page they are not rendered by MathJax.
Should  I explicitly specify the summary?

Thanks

**Comment by junfenglx** [comment]
And when I install plugin [render_math](https://github.com/barrysteyn/pelican_plugin-render_math),
the equantions in summary in index rendered correctly by MathJax

**Comment by junfenglx** [comment]
closed for no response.

**Comment by danielfrg** [comment]
No need to close it yet, I haven't had time to test this but I will do it as soon as i can.

**Pull request closed without merging**
