### PR TITLE
Create setup.py with package structure

### PR DESCRIPTION
**Pull request by schneiderfelipe**
This allows one to install the plugin as a regular package:

    $ pip install -e .

### CODE REVIEW

**Comment by danielfrg** [comment]
Thanks!
How would this look in the `pelicanconf.py`? Would you still have to download this project into `plugins`? I remember that was the only way I was able to make it work.

**Comment by schneiderfelipe** [comment]
> How would this look in the `pelicanconf.py`? Would you still have to download this project into `plugins`?

No need! After installing with pip, you'll be able to add the plugin directly to `PLUGINS`. Mine looks like

```python3
PLUGINS = ["extended_sitemap", "pelican_cite", "ipynb.markup", "pelican_shortener"]
```

The `pelican-ipynb` folder can be anywhere in your computer since the `-e` option of pip will symlink to it from somewhere like `/usr/local/lib/python3.6/dist-packages/` (that's the path in my computer).

By the way, this PR allows you to upload this project to [PyPI](https://pypi.org/).

**Comment by danielfrg** [comment]
Got it. I thought having it in the plugins directory was needed, i think i tried this at one point.
I will merge and I will push to PyPI when I got some free time.
Thanks!

**Comment by danielfrg** [comment]
You can find this now on PyPI: https://pypi.org/project/pelican-jupyter/

**Pull request merged**
